[project]
name = "py_service"
version = "0.1.0"
description = "FastAPI microservice"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.0"
]

[build-system]
requires = ["setuptools", "wheel"]
