global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: py-service
    metrics_path: /metrics
    static_configs:
      - targets: ["py-service:8000"]

  - job_name: js-service
    metrics_path: /metrics
    static_configs:
      - targets: ["js-service:3000"]
